steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/restaurants:$COMMIT_SHA', '.']
# Push the container to the Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/restaurants:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'restaurants'
  - '--image'
  - 'gcr.io/$PROJECT_ID/restaurants:$COMMIT_SHA'
  - '--region'
  - 'northamerica-northeast1'
  - '--port'
  - '80'
images:
- 'gcr.io/$PROJECT_ID/restaurants:$COMMIT_SHA'